name: Dristi-kerala workflow E-Treasury
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and analyze for Etreasury
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=solutions_etreasury -Dsonar.organization=solutions -Dsonar.host.url=https://sonarcloud.io/ 
        
      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io

      - name: Build and Push Docker image for etreasury-webpage
        run: |
           docker build  -t epayments:v1.0.0-${{ github.sha }} -f Dockerfile .
           docker tag epayments:v1.0.0-${{ github.sha }} pucarsolutionsdev.azurecr.io/epayments:v1.0.0-${{ github.sha }}
           docker push pucarsolutionsdev.azurecr.io/epayments:v1.0.0-${{ github.sha }}
        working-directory: treasury-webpage

      - name: Build and Push Docker image for etreasury-backend
        run: |
          docker build --build-arg WORK_DIR="treasury-backend" -t pucarsolutionsdev.azurecr.io/etreasury:v1.0.0-${{ github.sha }} -f build/maven/Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/etreasury:v1.0.0-${{ github.sha }}

      - name: Build and Push Docker image for etreasury-db
        run: |
          docker build -t etreasury_db:v1.0.0-${{ github.sha }}  .
          docker tag etreasury_db:v1.0.0-${{ github.sha }} pucarsolutionsdev.azurecr.io/etreasury_db:v1.0.0-${{ github.sha }}
          docker push pucarsolutionsdev.azurecr.io/etreasury_db:v1.0.0-${{ github.sha }}
        working-directory: treasury-backend/src/main/resources/db

      - name: Trigger Deployment Pipeline
        run: |
         curl -X POST \
         -H "Accept: application/vnd.github.v3+json" \
         -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
         https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/solutions-dev.yaml/dispatches \
         -d '{"ref":"Solutions-Pipeline"}'
